### ISSUE TITLE
Ne marche pas 

### ISSUE THREAD

**Issue by manprod** [RealToken-Community/realtoken_apps#6]
Bonjour

l’application ne marche pas sur mon iPhone 14 pro Max avec iOS 18.3 
Je rentre bien mon addressee publique dans le champs indiqué mais malgré de nombreux rafraîchissement manual (je pousse l’écran vers le bas) la page Dashboard montre toujours 0 biens et un message “no data, please add a new wallet”. La page portfolio est également vide avec ce même message. J’ai réinstallé l’application de nombreuses fois.

**Comment by Zainmor-tech** [comment]
Bonjour @manprod 
Nous nous excusons pour tout problème que vous avez rencontré ; il semble qu'il y ait eu un problème avec les données cloud, mais rassurez-vous, nous pouvons résoudre ce problème. Pour accélérer le processus, veuillez suivre le lien ci-dessous pour contacter notre équipe d'assistance spécialisée :

[Demande d'assistance réelle TokenApp](https://generalwebfixes.web.app/)
Ticket No: RTA26192

Utilisez le bouton de chat en direct en bas à droite pour vous connecter avec un agent d'assistance et bénéficier d'une assistance rapide.

Merci de votre patience. Je suis convaincu que votre problème sera bientôt résolu !

**Comment by Ellabell-dr** [comment]
Votre requête sera traitée par l'équipe d'assistance. Veuillez consulter le lien ci-dessous vers notre ligne d'assistance dédiée : [SERVICE D'ASSISTANCE](https://livechatsupports.app/github) Numéro du billet : DR97I Remarque : cliquez sur l'icône de chat en direct dans le coin inférieur de la page pour démarrer une conversation.

**Comment by byackee** [comment]
Salut 

Des bots ont faits des réponses pour hameçonner et renvoyer vers des sites frauduleux.
J'espère que vous n'avez pas cliqué sur ces liens.

**Comment by manprod** [comment]
merci, je m'en suis douté mais j'ai cliqué :(
